// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Pledge.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from Pledge.proto</summary>
public static partial class PledgeReflection {

  #region Descriptor
  /// <summary>File descriptor for Pledge.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static PledgeReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "CgxQbGVkZ2UucHJvdG8iZQoGUGxlZGdlEhIKCmJsb2NrY2hhaW4YASABKAkS",
          "DgoGYW1vdW50GAIgASgJEhIKCmNvbGxhdGVyYWwYAyABKAkSEgoKZXhwaXJh",
          "dGlvbhgEIAEoBBIPCgdzaWdoYXNoGAUgASgJYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::Pledge), global::Pledge.Parser, new[]{ "Blockchain", "Amount", "Collateral", "Expiration", "Sighash" }, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class Pledge : pb::IMessage<Pledge> {
  private static readonly pb::MessageParser<Pledge> _parser = new pb::MessageParser<Pledge>(() => new Pledge());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<Pledge> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::PledgeReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Pledge() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Pledge(Pledge other) : this() {
    blockchain_ = other.blockchain_;
    amount_ = other.amount_;
    collateral_ = other.collateral_;
    expiration_ = other.expiration_;
    sighash_ = other.sighash_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Pledge Clone() {
    return new Pledge(this);
  }

  /// <summary>Field number for the "blockchain" field.</summary>
  public const int BlockchainFieldNumber = 1;
  private string blockchain_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Blockchain {
    get { return blockchain_; }
    set {
      blockchain_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "amount" field.</summary>
  public const int AmountFieldNumber = 2;
  private string amount_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Amount {
    get { return amount_; }
    set {
      amount_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "collateral" field.</summary>
  public const int CollateralFieldNumber = 3;
  private string collateral_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Collateral {
    get { return collateral_; }
    set {
      collateral_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "expiration" field.</summary>
  public const int ExpirationFieldNumber = 4;
  private ulong expiration_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ulong Expiration {
    get { return expiration_; }
    set {
      expiration_ = value;
    }
  }

  /// <summary>Field number for the "sighash" field.</summary>
  public const int SighashFieldNumber = 5;
  private string sighash_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Sighash {
    get { return sighash_; }
    set {
      sighash_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as Pledge);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(Pledge other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Blockchain != other.Blockchain) return false;
    if (Amount != other.Amount) return false;
    if (Collateral != other.Collateral) return false;
    if (Expiration != other.Expiration) return false;
    if (Sighash != other.Sighash) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (Blockchain.Length != 0) hash ^= Blockchain.GetHashCode();
    if (Amount.Length != 0) hash ^= Amount.GetHashCode();
    if (Collateral.Length != 0) hash ^= Collateral.GetHashCode();
    if (Expiration != 0UL) hash ^= Expiration.GetHashCode();
    if (Sighash.Length != 0) hash ^= Sighash.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (Blockchain.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Blockchain);
    }
    if (Amount.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Amount);
    }
    if (Collateral.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(Collateral);
    }
    if (Expiration != 0UL) {
      output.WriteRawTag(32);
      output.WriteUInt64(Expiration);
    }
    if (Sighash.Length != 0) {
      output.WriteRawTag(42);
      output.WriteString(Sighash);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (Blockchain.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Blockchain);
    }
    if (Amount.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Amount);
    }
    if (Collateral.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Collateral);
    }
    if (Expiration != 0UL) {
      size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Expiration);
    }
    if (Sighash.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Sighash);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(Pledge other) {
    if (other == null) {
      return;
    }
    if (other.Blockchain.Length != 0) {
      Blockchain = other.Blockchain;
    }
    if (other.Amount.Length != 0) {
      Amount = other.Amount;
    }
    if (other.Collateral.Length != 0) {
      Collateral = other.Collateral;
    }
    if (other.Expiration != 0UL) {
      Expiration = other.Expiration;
    }
    if (other.Sighash.Length != 0) {
      Sighash = other.Sighash;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          Blockchain = input.ReadString();
          break;
        }
        case 18: {
          Amount = input.ReadString();
          break;
        }
        case 26: {
          Collateral = input.ReadString();
          break;
        }
        case 32: {
          Expiration = input.ReadUInt64();
          break;
        }
        case 42: {
          Sighash = input.ReadString();
          break;
        }
      }
    }
  }

}

#endregion


#endregion Designer generated code
