// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: RepaymentOrder.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from RepaymentOrder.proto</summary>
public static partial class RepaymentOrderReflection {

  #region Descriptor
  /// <summary>File descriptor for RepaymentOrder.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static RepaymentOrderReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChRSZXBheW1lbnRPcmRlci5wcm90byLKAQoOUmVwYXltZW50T3JkZXISEgoK",
          "YmxvY2tjaGFpbhgBIAEoCRITCgtzcmNfYWRkcmVzcxgCIAEoCRITCgtkc3Rf",
          "YWRkcmVzcxgDIAEoCRIOCgZhbW91bnQYBCABKAkSEgoKZXhwaXJhdGlvbhgF",
          "IAEoBBINCgVibG9jaxgGIAEoCRIMCgRkZWFsGAcgASgJEhYKDnByZXZpb3Vz",
          "X293bmVyGAggASgJEhAKCHRyYW5zZmVyGAkgASgJEg8KB3NpZ2hhc2gYCiAB",
          "KAliBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::RepaymentOrder), global::RepaymentOrder.Parser, new[]{ "Blockchain", "SrcAddress", "DstAddress", "Amount", "Expiration", "Block", "Deal", "PreviousOwner", "Transfer", "Sighash" }, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class RepaymentOrder : pb::IMessage<RepaymentOrder> {
  private static readonly pb::MessageParser<RepaymentOrder> _parser = new pb::MessageParser<RepaymentOrder>(() => new RepaymentOrder());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<RepaymentOrder> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::RepaymentOrderReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public RepaymentOrder() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public RepaymentOrder(RepaymentOrder other) : this() {
    blockchain_ = other.blockchain_;
    srcAddress_ = other.srcAddress_;
    dstAddress_ = other.dstAddress_;
    amount_ = other.amount_;
    expiration_ = other.expiration_;
    block_ = other.block_;
    deal_ = other.deal_;
    previousOwner_ = other.previousOwner_;
    transfer_ = other.transfer_;
    sighash_ = other.sighash_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public RepaymentOrder Clone() {
    return new RepaymentOrder(this);
  }

  /// <summary>Field number for the "blockchain" field.</summary>
  public const int BlockchainFieldNumber = 1;
  private string blockchain_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Blockchain {
    get { return blockchain_; }
    set {
      blockchain_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "src_address" field.</summary>
  public const int SrcAddressFieldNumber = 2;
  private string srcAddress_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string SrcAddress {
    get { return srcAddress_; }
    set {
      srcAddress_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "dst_address" field.</summary>
  public const int DstAddressFieldNumber = 3;
  private string dstAddress_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string DstAddress {
    get { return dstAddress_; }
    set {
      dstAddress_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "amount" field.</summary>
  public const int AmountFieldNumber = 4;
  private string amount_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Amount {
    get { return amount_; }
    set {
      amount_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "expiration" field.</summary>
  public const int ExpirationFieldNumber = 5;
  private ulong expiration_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ulong Expiration {
    get { return expiration_; }
    set {
      expiration_ = value;
    }
  }

  /// <summary>Field number for the "block" field.</summary>
  public const int BlockFieldNumber = 6;
  private string block_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Block {
    get { return block_; }
    set {
      block_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "deal" field.</summary>
  public const int DealFieldNumber = 7;
  private string deal_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Deal {
    get { return deal_; }
    set {
      deal_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "previous_owner" field.</summary>
  public const int PreviousOwnerFieldNumber = 8;
  private string previousOwner_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string PreviousOwner {
    get { return previousOwner_; }
    set {
      previousOwner_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "transfer" field.</summary>
  public const int TransferFieldNumber = 9;
  private string transfer_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Transfer {
    get { return transfer_; }
    set {
      transfer_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "sighash" field.</summary>
  public const int SighashFieldNumber = 10;
  private string sighash_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Sighash {
    get { return sighash_; }
    set {
      sighash_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as RepaymentOrder);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(RepaymentOrder other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Blockchain != other.Blockchain) return false;
    if (SrcAddress != other.SrcAddress) return false;
    if (DstAddress != other.DstAddress) return false;
    if (Amount != other.Amount) return false;
    if (Expiration != other.Expiration) return false;
    if (Block != other.Block) return false;
    if (Deal != other.Deal) return false;
    if (PreviousOwner != other.PreviousOwner) return false;
    if (Transfer != other.Transfer) return false;
    if (Sighash != other.Sighash) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (Blockchain.Length != 0) hash ^= Blockchain.GetHashCode();
    if (SrcAddress.Length != 0) hash ^= SrcAddress.GetHashCode();
    if (DstAddress.Length != 0) hash ^= DstAddress.GetHashCode();
    if (Amount.Length != 0) hash ^= Amount.GetHashCode();
    if (Expiration != 0UL) hash ^= Expiration.GetHashCode();
    if (Block.Length != 0) hash ^= Block.GetHashCode();
    if (Deal.Length != 0) hash ^= Deal.GetHashCode();
    if (PreviousOwner.Length != 0) hash ^= PreviousOwner.GetHashCode();
    if (Transfer.Length != 0) hash ^= Transfer.GetHashCode();
    if (Sighash.Length != 0) hash ^= Sighash.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (Blockchain.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Blockchain);
    }
    if (SrcAddress.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(SrcAddress);
    }
    if (DstAddress.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(DstAddress);
    }
    if (Amount.Length != 0) {
      output.WriteRawTag(34);
      output.WriteString(Amount);
    }
    if (Expiration != 0UL) {
      output.WriteRawTag(40);
      output.WriteUInt64(Expiration);
    }
    if (Block.Length != 0) {
      output.WriteRawTag(50);
      output.WriteString(Block);
    }
    if (Deal.Length != 0) {
      output.WriteRawTag(58);
      output.WriteString(Deal);
    }
    if (PreviousOwner.Length != 0) {
      output.WriteRawTag(66);
      output.WriteString(PreviousOwner);
    }
    if (Transfer.Length != 0) {
      output.WriteRawTag(74);
      output.WriteString(Transfer);
    }
    if (Sighash.Length != 0) {
      output.WriteRawTag(82);
      output.WriteString(Sighash);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (Blockchain.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Blockchain);
    }
    if (SrcAddress.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(SrcAddress);
    }
    if (DstAddress.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(DstAddress);
    }
    if (Amount.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Amount);
    }
    if (Expiration != 0UL) {
      size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Expiration);
    }
    if (Block.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Block);
    }
    if (Deal.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Deal);
    }
    if (PreviousOwner.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(PreviousOwner);
    }
    if (Transfer.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Transfer);
    }
    if (Sighash.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Sighash);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(RepaymentOrder other) {
    if (other == null) {
      return;
    }
    if (other.Blockchain.Length != 0) {
      Blockchain = other.Blockchain;
    }
    if (other.SrcAddress.Length != 0) {
      SrcAddress = other.SrcAddress;
    }
    if (other.DstAddress.Length != 0) {
      DstAddress = other.DstAddress;
    }
    if (other.Amount.Length != 0) {
      Amount = other.Amount;
    }
    if (other.Expiration != 0UL) {
      Expiration = other.Expiration;
    }
    if (other.Block.Length != 0) {
      Block = other.Block;
    }
    if (other.Deal.Length != 0) {
      Deal = other.Deal;
    }
    if (other.PreviousOwner.Length != 0) {
      PreviousOwner = other.PreviousOwner;
    }
    if (other.Transfer.Length != 0) {
      Transfer = other.Transfer;
    }
    if (other.Sighash.Length != 0) {
      Sighash = other.Sighash;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          Blockchain = input.ReadString();
          break;
        }
        case 18: {
          SrcAddress = input.ReadString();
          break;
        }
        case 26: {
          DstAddress = input.ReadString();
          break;
        }
        case 34: {
          Amount = input.ReadString();
          break;
        }
        case 40: {
          Expiration = input.ReadUInt64();
          break;
        }
        case 50: {
          Block = input.ReadString();
          break;
        }
        case 58: {
          Deal = input.ReadString();
          break;
        }
        case 66: {
          PreviousOwner = input.ReadString();
          break;
        }
        case 74: {
          Transfer = input.ReadString();
          break;
        }
        case 82: {
          Sighash = input.ReadString();
          break;
        }
      }
    }
  }

}

#endregion


#endregion Designer generated code
